### ISSUE TITLE
Package is incompatible with current setuptools releases

### ISSUE THREAD

**Issue by haubenr** [icholy/durationpy#16]
The durationpy package (version 0.7) can't be installed due to an incompatibility with recent versions of the setuptools package. When running `pip3 install -U durationpy` on a python3 instance that makes use of setuptools versions 71.0.0 and later the installation fails:

```
Collecting durationpy
  Using cached durationpy-0.7.tar.gz (3.2 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [53 lines of output]
      /usr/local/lib/python3.9/site-packages/setuptools/dist.py:458: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'description-file' will not be supported in future
              versions. Please use the underscore name 'description_file' instead.

              This deprecation is overdue, please update your project and remove deprecated
              calls to avoid build errors in the future.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      running egg_info
      creating /tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info
      writing /tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info/PKG-INFO
      writing dependency_links to /tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info/dependency_links.txt
      writing top-level names to /tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info/top_level.txt
      writing manifest file '/tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info/SOURCES.txt'
      reading manifest file '/tmp/pip-pip-egg-info-edc6fbr8/durationpy.egg-info/SOURCES.txt'
      adding license file 'LICENSE'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-n0jlbnp0/durationpy_a7d027a4f8de4830a6154a389911846b/setup.py", line 3, in <module>
          setup(
        File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 108, in setup
          return distutils.core.setup(**attrs)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 184, in setup
          return run_commands(dist)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
          dist.run_commands()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
          self.run_command(cmd)
        File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 956, in run_command
          super().run_command(command)
        File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
          cmd_obj.run()
        File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 310, in run
          self.find_sources()
        File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 318, in find_sources
          mm.run()
        File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 544, in run
          self.prune_file_list()
        File "/usr/local/lib/python3.9/site-packages/setuptools/command/egg_info.py", line 610, in prune_file_list
          base_dir = self.distribution.get_fullname()
        File "/usr/local/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 266, in get_fullname
          return _distribution_fullname(self.get_name(), self.get_version())
        File "/usr/local/lib/python3.9/site-packages/setuptools/_core_metadata.py", line 284, in _distribution_fullname
          canonicalize_version(version, strip_trailing_zero=False),
      TypeError: canonicalize_version() got an unexpected keyword argument 'strip_trailing_zero'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

This seems to be caused by `description-file` in setup.cfg.

**Comment by icholy** [comment]
Fix is published in 0.8
