### ISSUE TITLE
Module is missing a wheel package

### ISSUE THREAD

**Issue by thomascellerier** [icholy/durationpy#17]
I have a debian based container image that internally depends on the kubernetes package.
It installed fine without setuptools due to containing only .whl packages.

Now kubernetes added a dependency on durationpy but it is missing a wheel package, causing the following error on installation:
```
26.91 Collecting durationpy>=0.7 (from kubernetes->-r /build/project/building/operator-requirements.txt (line 1))
27.02   Downloading https://[internal proxy hostname redacted]/durationpy-0.7.tar.gz (3.2 kB)
27.03   Preparing metadata (setup.py): started
27.06   Preparing metadata (setup.py): finished with status 'error'
28.12   error: subprocess-exited-with-error
28.12
28.12   × python setup.py egg_info did not run successfully.
28.12   │ exit code: 1
28.12   ╰─> [6 lines of output]
28.12       Traceback (most recent call last):
28.12         File "<string>", line 2, in <module>
28.12         File "<pip-setuptools-caller>", line 34, in <module>
28.12         File "/tmp/pip-install-90w071yb/durationpy_471a572085434285a8c661fe74701e9a/setup.py", line 1, in <module>
28.12           from setuptools import setup
28.12       ImportError: cannot import name 'setup' from 'setuptools' (unknown location)
28.12       [end of output]
28.12
28.12   note: This error originates from a subprocess, and is likely not a problem with pip.
28.13 error: metadata-generation-failed
28.13
28.13 × Encountered error while generating package metadata.
28.13 ╰─> See above for output.
28.13
28.13 note: This is an issue with the package mentioned above, not pip.
28.13 hint: See above for details.
```

This required installing the following dependency prior to pip installing `python3-setuptools` when no other of our dependencies required it.

It would be very nice if durationpy also provided a .whl package.

**Comment by icholy** [comment]
0.9 has a wheel package.

**Comment by thomascellerier** [comment]
Thanks for the quick fix!
